package com.pawpixel.sprite

import com.pawpixel.core.TaskKind

/**
 * The app's icons, drawn as 12x12 pixel grids in the same hand as the pet, so a bowl in a button
 * and the bowl on the floor are one style. 'x' is the ink (tinted by the UI), 'o' a lighter ink,
 * '.' nothing. Emoji were dropped: they render differently on every phone and read as placeholders.
 */
class PixelIcon(val rows: List<String>) {
    val width = rows.maxOf { it.length }
    val height = rows.size
    /** 0 = empty, 1 = ink, 2 = light ink. */
    fun cell(x: Int, y: Int): Int = when (rows[y].getOrNull(x)) { 'x' -> 1; 'o' -> 2; else -> 0 }
}

object PixelIcons {
    private fun g(vararg rows: String) = PixelIcon(rows.toList())

    val BOWL = g(
        "............",
        "....xxxx....",
        "...xooxox...",
        "..xooxooox..",
        ".xxxxxxxxxx.",
        "xoooooooooox",
        "xoooooooooox",
        ".xxxxxxxxxx.",
        "..xoooooox..",
        "...xxxxxx...",
        "............",
        "............",
    )
    val DROP = g(
        ".....x......",
        "....xox.....",
        "....xox.....",
        "...xooox....",
        "...xooox....",
        "..xoooooх...".replace('х', 'x'),
        "..xoooooox..",
        ".xoooooooox.",
        ".xoooooooox.",
        ".xxoooooxxx.",
        "..xxooooxx..",
        "....xxxx....",
    )
    val PAW = g(
        "............",
        "..xx....xx..",
        ".xoox..xoox.",
        ".xoox..xoox.",
        "xx.xx..xx.xx",
        "xoox....xoox",
        ".xx..xx..xx.",
        "....xoox....",
        "...xoooox...",
        "..xoooooox..",
        "..xoooooox..",
        "...xxxxxx...",
    )
    val BALL = g(
        "............",
        "....xxxx....",
        "..xxoooxxx..",
        ".xoxoooooxx.",
        ".xoxoooooox.",
        "xoooxoooooox",
        "xooooxooooox",
        "xoooooxoooox",
        ".xooooooxox.",
        ".xoooooooxx.",
        "..xxoooxxx..",
        "....xxxx....",
    )
    val PILL = g(
        "............",
        "............",
        "............",
        "..xxxxxxxx..",
        ".xooooxxxxx.",
        "xoooooxxxxxx",
        "xoooooxxxxxx",
        ".xooooxxxxx.",
        "..xxxxxxxx..",
        "............",
        "............",
        "............",
    )
    val COMB = g(
        "............",
        ".xxxxxxxxxx.",
        "xoooooooooox",
        "xoooooooooox",
        ".xxxxxxxxxx.",
        ".x.x.x.x.x..",
        ".x.x.x.x.x..",
        ".x.x.x.x.x..",
        ".x.x.x.x.x..",
        ".x.x.x.x.x..",
        "............",
        "............",
    )
    val SCOOP = g(
        "........xx..",
        ".......xoox.",
        "......xoox..",
        ".....xoox...",
        "....xoox....",
        "...xxxx.....",
        "..xooooxx...",
        ".xoooooox...",
        ".xoooooox...",
        ".xoooooox...",
        ".xxxxxxxx...",
        "............",
    )
    val SYRINGE = g(
        "..........xx",
        ".........xox",
        "........xox.",
        ".......xox..",
        "....xxxxxx..",
        "...xoooox...",
        "..xoxoox....",
        ".xoooox.....",
        "xoooox......",
        "xxoox.......",
        "x.xx........",
        "xx..........",
    )
    val WORM = g(
        "............",
        "............",
        "..xxx.......",
        ".xoooxx.....",
        ".xo.oooxx...",
        "..xxxoooox..",
        ".....xxoox..",
        "...xxoooox..",
        "..xoooooxx..",
        "..xooooox...",
        "...xxxxx....",
        "............",
    )
    val SHIELD = g(
        "............",
        ".xxxxxxxxxx.",
        "xooooxooooox",
        "xoooxoxooox.",
        "xooxoooxoox.",
        "xoxoooooxox.",
        "xooxoooxoox.",
        ".xoooxoooox.",
        ".xooooooox..",
        "..xoooooox..",
        "...xoooox...",
        "....xxxx....",
    )
    val STETHO = g(
        "............",
        "..xx....xx..",
        "..xo....ox..",
        "..xo....ox..",
        "...xo..ox...",
        "....xooox...",
        ".....xox....",
        ".....xo.....",
        ".....xo..xx.",
        "......xoxoox",
        ".......xxxox",
        "..........xx",
    )
    val HEART = g(
        "............",
        "..xxx..xxx..",
        ".xooox.xoox.",
        "xoooooxooox.",
        "xooooooooox.",
        "xooooooooox.",
        ".xoooooooox.",
        "..xooooooox.",
        "...xooooox..",
        "....xooox...",
        ".....xox....",
        "......x.....",
    )
    val SCALE = g(
        "............",
        "..xxxxxxxx..",
        ".xooooooooх.".replace('х', 'x'),
        "xoooxxxxooox",
        "xooxooooxoox",
        "xoooxxxxooox",
        "xooooooooooх".replace('х', 'x'),
        "xooooooooooх".replace('х', 'x'),
        "xooooooooooх".replace('х', 'x'),
        ".xooooooooх.".replace('х', 'x'),
        "..xxxxxxxx..",
        "............",
    )
    val SHIRT = g(
        "............",
        "..xx....xx..",
        ".xoxxxxxxox.",
        "xooooooooox.",
        "xooxooooxoox",
        "xxoooooooxxx",
        ".xooooooox..",
        ".xooooooox..",
        ".xooooooox..",
        ".xooooooox..",
        ".xxxxxxxxx..",
        "............",
    )
    val SPARKLE = g(
        ".....x......",
        ".....x......",
        "....xox.....",
        ".xxxoooxxx..",
        "..xooooox...",
        "...xoooox...",
        "..xoooooox..",
        ".xxxoooxxx..",
        "....xox..x..",
        ".....x..xox.",
        ".........x..",
        "............",
    )
    val SHARE = g(
        "............",
        ".......xx...",
        "......xoox..",
        ".....xoooox.",
        "....xoxoxox.",
        ".....x.o.x..",
        ".xxxxx.o.xx.",
        ".xoooo.o.ox.",
        ".xoooooooox.",
        ".xoooooooox.",
        ".xxxxxxxxxx.",
        "............",
    )
    val PIN = g(
        "............",
        "....xxxx....",
        "...xooooх...".replace('х', 'x'),
        "..xooxxoox..",
        "..xoxooxox..",
        "..xoxooxox..",
        "..xooxxoox..",
        "...xooooox..",
        "....xooox...",
        ".....xox....",
        "......x.....",
        "............",
    )
    val HOUSE = g(
        "......x.....",
        ".....xox....",
        "....xooox...",
        "...xoooooox.",
        "..xooooooox.",
        ".xoooooooox.",
        "xxxoooooooxx",
        "..xooxxooox.",
        "..xooxoxoox.",
        "..xooxoxoox.",
        "..xxxxxxxxx.",
        "............",
    )
    val GEAR = g(
        "....xxxx....",
        ".x.xooooх.x.".replace('х', 'x'),
        "xoxoooooxox.",
        ".xooxxxxoox.",
        "xooxooooxoox",
        "xooxooooxoox",
        "xooxooooxoox",
        ".xooxxxxoox.",
        "xoxoooooxox.",
        ".x.xooooх.x.".replace('х', 'x'),
        "....xxxx....",
        "............",
    )
    val BELL = g(
        ".....xx.....",
        "....xoox....",
        "...xooooх...".replace('х', 'x'),
        "..xoooooox..",
        "..xoooooox..",
        "..xoooooox..",
        ".xooooooooх.".replace('х', 'x'),
        ".xooooooooх.".replace('х', 'x'),
        "xxxxxxxxxxxx",
        ".....xx.....",
        "....xoox....",
        ".....xx.....",
    )
    val GLOBE = g(
        "....xxxx....",
        "..xxoxoxxx..",
        ".xooxooox.x.",
        ".xxxxxxxxxx.",
        "xoooxoooxoox",
        "xoooxoooxoox",
        "xxxxxxxxxxxx",
        "xoooxoooxoox",
        ".xooxooox.x.",
        ".xxxxxxxxxx.",
        "..xxoxoxxx..",
        "....xxxx....",
    )
    val BAG = g(
        "............",
        "....xxxx....",
        "....xoox....",
        ".xxxxxxxxxx.",
        "xooooooooooх".replace('х', 'x'),
        "xoxoooooooxх".replace('х', 'x'),
        "xoxoooooooxх".replace('х', 'x'),
        "xoxoooooooxх".replace('х', 'x'),
        "xoxoooooooxх".replace('х', 'x'),
        "xooooooooooх".replace('х', 'x'),
        ".xxxxxxxxxx.",
        "............",
    )
    val MOON = g(
        "....xxxx....",
        "..xxooooxx..",
        ".xoooooxx...",
        ".xoooox.....",
        "xooooox.....",
        "xoooox......",
        "xoooox......",
        "xooooox.....",
        ".xoooox.....",
        ".xoooooxx...",
        "..xxooooxx..",
        "....xxxx....",
    )
    val STAR = g(
        ".....xx.....",
        ".....xx.....",
        "....xoox....",
        "....xoox....",
        "xxxxxooxxxxx",
        ".xoooooooox.",
        "..xoooooox..",
        "...xooooox..",
        "...xoooox...",
        "..xoooooox..",
        "..xoxxxxox..",
        "..x......x..",
    )
    val SAVE = g(
        "............",
        "xxxxxxxxxxx.",
        "xoxoooooxox.",
        "xoxoooooxoox",
        "xoxxxxxxxoox",
        "xoooooooooox",
        "xoooooooooox",
        "xoxxxxxxxoox",
        "xoxoooooxoox",
        "xoxoooooxoox",
        "xxxxxxxxxxxx",
        "............",
    )
    val LOCK = g(
        "............",
        "...xxxxxx...",
        "..xoxxxxox..",
        "..xo....ox..",
        "..xo....ox..",
        ".xxxxxxxxxx.",
        ".xoooooooox.",
        ".xoooxxooox.",
        ".xoooxxooox.",
        ".xooooxooox.",
        ".xxxxxxxxxx.",
        "............",
    )
    val CAMERA = g(
        "............",
        "...xxxx.....",
        "xxxxooxxxxxx",
        "xooooooooooх".replace('х', 'x'),
        "xoooxxxxooox",
        "xooxooooxoox",
        "xooxooooxoox",
        "xooxooooxoox",
        "xoooxxxxooox",
        "xooooooooooх".replace('х', 'x'),
        "xxxxxxxxxxxx",
        "............",
    )
    val CHEVRON_LEFT = g(
        "............",
        "............",
        "......xx....",
        ".....xox....",
        "....xox.....",
        "...xox......",
        "...xox......",
        "....xox.....",
        ".....xox....",
        "......xx....",
        "............",
        "............",
    )
    val CHEVRON_RIGHT = g(
        "............",
        "............",
        "....xx......",
        "....xox.....",
        ".....xox....",
        "......xox...",
        "......xox...",
        ".....xox....",
        "....xox.....",
        "....xx......",
        "............",
        "............",
    )
    val PENCIL = g(
        "........xxx.",
        ".......xoox.",
        "......xoox..",
        ".....xoox...",
        "....xoox....",
        "...xoox.....",
        "..xoox......",
        ".xoox.......",
        "xxox........",
        "xox.........",
        "xx..........",
        "............",
    )
    val PLUS = g(
        "............",
        ".....xx.....",
        ".....xx.....",
        ".....xx.....",
        ".....xx.....",
        ".xxxxxxxxxx.",
        ".xxxxxxxxxx.",
        ".....xx.....",
        ".....xx.....",
        ".....xx.....",
        ".....xx.....",
        "............",
    )
    val CHECK = g(
        "............",
        "..........x.",
        ".........xx.",
        "........xx..",
        ".......xx...",
        "......xx....",
        ".x...xx.....",
        ".xx.xx......",
        "..xxx.......",
        "...x........",
        "............",
        "............",
    )
    val CLOSE = g(
        "............",
        ".xx......xx.",
        ".xxx....xxx.",
        "..xxx..xxx..",
        "...xxxxxx...",
        "....xxxx....",
        "....xxxx....",
        "...xxxxxx...",
        "..xxx..xxx..",
        ".xxx....xxx.",
        ".xx......xx.",
        "............",
    )
    val DICE = g(
        "............",
        ".xxxxxxxxxx.",
        "xoooooooooox",
        "xoxooooooxox",
        "xoooooooooox",
        "xoooooooooox",
        "xooooxxooooх".replace('х', 'x'),
        "xooooxxooooх".replace('х', 'x'),
        "xoooooooooox",
        "xoxooooooxox",
        "xoooooooooox",
        ".xxxxxxxxxx.",
    )
    /** Three dots: "more". */
    val DOTS = g(
        "............",
        "............",
        "............",
        "............",
        ".xx..xx..xx.",
        "xooxxooxxoox",
        "xooxxooxxoox",
        ".xx..xx..xx.",
        "............",
        "............",
        "............",
        "............",
    )
    val PARTY = g(
        "..........x.",
        "........o.x.",
        ".......x..o.",
        "......xox...",
        ".....xoox.o.",
        "....xooox...",
        "...xoooox...",
        "..xoooox..x.",
        ".xoooox.....",
        "xxxxxx......",
        "............",
        "............",
    )
    val PHONE = g(
        "...xxxxxx...",
        "..xooooooх..".replace('х', 'x'),
        "..xoxxxxox..",
        "..xoxooxox..",
        "..xoxooxox..",
        "..xoxooxox..",
        "..xoxooxox..",
        "..xoxooxox..",
        "..xoxxxxox..",
        "..xooooooх..".replace('х', 'x'),
        "...xxxxxx...",
        "............",
    )
    val PEOPLE = g(
        "............",
        "...xx..xx...",
        "..xoox.xoox.",
        "..xoox.xoox.",
        "...xx..xx...",
        "..xxxx.xxxx.",
        ".xooooxooox.",
        ".xooooxooox.",
        ".xooooxooox.",
        ".xooooxooox.",
        ".xxxxxxxxxx.",
        "............",
    )

    /** The icon of a care kind. */
    fun forKind(kind: TaskKind): PixelIcon = when (kind) {
        TaskKind.FEED -> BOWL
        TaskKind.WATER -> DROP
        TaskKind.WALK -> PAW
        TaskKind.PLAY -> BALL
        TaskKind.MEDS -> PILL
        TaskKind.GROOM -> COMB
        TaskKind.LITTER -> SCOOP
        TaskKind.VACCINE -> SYRINGE
        TaskKind.DEWORM -> WORM
        TaskKind.FLEA_TICK -> SHIELD
        TaskKind.VET -> STETHO
    }
}
